-- 003-seed-profiles.sql
-- Seeds 50 prominent Iranian political and public figures as profiles.
-- Safe to run multiple times (ON CONFLICT (promtic_identifier->>'external_id') DO NOTHING via unique index).
-- Run AFTER 002-admin-migration.sql.

BEGIN;

-- Temporary unique index on external_id to make upsert safe
CREATE UNIQUE INDEX IF NOT EXISTS idx_profiles_promtic_ext_id
  ON profiles ((promtic_identifier->>'external_id'))
  WHERE promtic_identifier IS NOT NULL;

INSERT INTO profiles (id, name, role, organization, keywords, excluded_keywords, sort_criteria, plan, primary_color, promtic_identifier, is_active, created_at, updated_at)
VALUES
(gen_random_uuid(),'سید مجتبی خامنهای','رهبر معظم انقلاب','دفتر مقام معظم رهبری',ARRAY['خامنهای','رهبر انقلاب','رهبری'],ARRAY[]::text[],'recent','enterprise','#8B0000','{"external_id":"khamenei","name":"سید مجتبی خامنهای","type":"political_figure"}'::jsonb,true,NOW(),NOW()),
(gen_random_uuid(),'مسعود پزشکیان','رئیس جمهور','ریاست جمهوری',ARRAY['پزشکیان','رئیس جمهور','دولت'],ARRAY[]::text[],'recent','enterprise','#1565C0','{"external_id":"pezeshkian","name":"مسعود پزشکیان","type":"political_figure"}'::jsonb,true,NOW(),NOW()),
(gen_random_uuid(),'محمدباقر قالیباف','رئیس مجلس شورای اسلامی','مجلس شورای اسلامی',ARRAY['قالیباف','رئیس مجلس','مجلس'],ARRAY[]::text[],'recent','enterprise','#1e6091','{"external_id":"ghalibaf","name":"محمدباقر قالیباف","type":"political_figure"}'::jsonb,true,NOW(),NOW()),
(gen_random_uuid(),'غلامحسین محسنی اژهای','رئیس قوه قضائیه','قوه قضائیه',ARRAY['اژهای','قوه قضائیه','قضا'],ARRAY[]::text[],'recent','enterprise','#4A148C','{"external_id":"ejei","name":"غلامحسین محسنی اژهای","type":"political_figure"}'::jsonb,true,NOW(),NOW()),
(gen_random_uuid(),'احمد جنتی','دبیر شورای نگهبان','شورای نگهبان',ARRAY['جنتی','شورای نگهبان'],ARRAY[]::text[],'recent','standard','#37474F','{"external_id":"jannati","name":"احمد جنتی","type":"political_figure"}'::jsonb,true,NOW(),NOW()),
(gen_random_uuid(),'صادق لاریجانی','رئیس مجمع تشخیص مصلحت نظام','مجمع تشخیص مصلحت نظام',ARRAY['لاریجانی','مجمع تشخیص','صادق لاریجانی'],ARRAY[]::text[],'recent','enterprise','#1B5E20','{"external_id":"sadegh_larijani","name":"صادق لاریجانی","type":"political_figure"}'::jsonb,true,NOW(),NOW()),
(gen_random_uuid(),'سعید جلیلی','عضو مجمع تشخیص و دبیر پیشین شورای عالی امنیت ملی','مجمع تشخیص مصلحت نظام',ARRAY['جلیلی','سعید جلیلی','امنیت ملی'],ARRAY[]::text[],'recent','standard','#BF360C','{"external_id":"jalili","name":"سعید جلیلی","type":"political_figure"}'::jsonb,true,NOW(),NOW()),
(gen_random_uuid(),'محمدرضا عارف','معاون اول رئیسجمهور','ریاست جمهوری',ARRAY['عارف','محمدرضا عارف','معاون اول'],ARRAY[]::text[],'recent','standard','#006064','{"external_id":"aref","name":"محمدرضا عارف","type":"political_figure"}'::jsonb,true,NOW(),NOW()),
(gen_random_uuid(),'اسحاق جهانگیری','معاون پیشین رئیس جمهور','دولت',ARRAY['جهانگیری','اسحاق جهانگیری'],ARRAY[]::text[],'recent','standard','#33691E','{"external_id":"jahangiri","name":"اسحاق جهانگیری","type":"political_figure"}'::jsonb,true,NOW(),NOW()),
(gen_random_uuid(),'غلامعلی حداد عادل','رئیس مجلس پیشین','مجلس شورای اسلامی',ARRAY['حداد عادل','غلامعلی حداد'],ARRAY[]::text[],'recent','standard','#4E342E','{"external_id":"haddad_adel","name":"غلامعلی حداد عادل","type":"political_figure"}'::jsonb,true,NOW(),NOW()),
(gen_random_uuid(),'حسن روحانی','رئیس جمهور پیشین','دولت',ARRAY['روحانی','حسن روحانی'],ARRAY[]::text[],'recent','standard','#0277BD','{"external_id":"rouhani","name":"حسن روحانی","type":"political_figure"}'::jsonb,true,NOW(),NOW()),
(gen_random_uuid(),'محمود احمدینژاد','رئیس جمهور پیشین','دولت',ARRAY['احمدینژاد','محمود احمدی نژاد'],ARRAY[]::text[],'recent','standard','#E65100','{"external_id":"ahmadinejad","name":"محمود احمدینژاد","type":"political_figure"}'::jsonb,true,NOW(),NOW()),
(gen_random_uuid(),'سید محمد خاتمی','رئیس جمهور پیشین','دولت',ARRAY['خاتمی','سید محمد خاتمی'],ARRAY[]::text[],'recent','standard','#00695C','{"external_id":"khatami","name":"سید محمد خاتمی","type":"political_figure"}'::jsonb,true,NOW(),NOW()),
(gen_random_uuid(),'محسن رضایی','مشاور رهبری','دفتر مقام معظم رهبری',ARRAY['محسن رضایی','رضایی'],ARRAY[]::text[],'recent','standard','#558B2F','{"external_id":"rezaei","name":"محسن رضایی","type":"political_figure"}'::jsonb,true,NOW(),NOW()),
(gen_random_uuid(),'احمد وحیدی','فرمانده کل سپاه پاسداران','سپاه پاسداران',ARRAY['وحیدی','احمد وحیدی','سپاه'],ARRAY[]::text[],'recent','standard','#212121','{"external_id":"vahidi","name":"احمد وحیدی","type":"political_figure"}'::jsonb,true,NOW(),NOW()),
(gen_random_uuid(),'امیر حاتمی','فرمانده کل ارتش','ارتش جمهوری اسلامی ایران',ARRAY['امیر حاتمی','حاتمی','ارتش'],ARRAY[]::text[],'recent','standard','#263238','{"external_id":"hatami_army","name":"امیر حاتمی","type":"political_figure"}'::jsonb,true,NOW(),NOW()),
(gen_random_uuid(),'اسماعیل قاآنی','فرمانده نیروی قدس سپاه','سپاه پاسداران',ARRAY['قاآنی','اسماعیل قاآنی','نیروی قدس'],ARRAY[]::text[],'recent','standard','#1A237E','{"external_id":"qaani","name":"اسماعیل قاآنی","type":"political_figure"}'::jsonb,true,NOW(),NOW()),
(gen_random_uuid(),'اسکندر مومنی','وزیر کشور','وزارت کشور',ARRAY['مومنی','اسکندر مومنی','وزیر کشور'],ARRAY[]::text[],'recent','standard','#37474F','{"external_id":"momeni","name":"اسکندر مومنی","type":"political_figure"}'::jsonb,true,NOW(),NOW()),
(gen_random_uuid(),'سیدمجید موسوی','فرمانده نیروی هوافضای سپاه','سپاه پاسداران',ARRAY['سیدمجید موسوی','موسوی','هوافضای سپاه'],ARRAY[]::text[],'recent','standard','#0D47A1','{"external_id":"mousavi_aerospace","name":"سیدمجید موسوی","type":"political_figure"}'::jsonb,true,NOW(),NOW()),
(gen_random_uuid(),'امیر حیدری','فرمانده نیروی زمینی ارتش','ارتش جمهوری اسلامی ایران',ARRAY['امیر حیدری','حیدری','نیروی زمینی'],ARRAY[]::text[],'recent','standard','#1B5E20','{"external_id":"heydari_army","name":"امیر حیدری","type":"political_figure"}'::jsonb,true,NOW(),NOW()),
(gen_random_uuid(),'محمد اسلامی','رئیس سازمان انرژی اتمی','سازمان انرژی اتمی ایران',ARRAY['محمد اسلامی','اسلامی','انرژی اتمی','هستهای'],ARRAY[]::text[],'recent','standard','#4A148C','{"external_id":"eslami_atomic","name":"محمد اسلامی","type":"political_figure"}'::jsonb,true,NOW(),NOW()),
(gen_random_uuid(),'عبدالناصر همتی','رئیس کل بانک مرکزی','بانک مرکزی',ARRAY['همتی','عبدالناصر همتی','بانک مرکزی'],ARRAY[]::text[],'recent','standard','#006064','{"external_id":"hemmati","name":"عبدالناصر همتی","type":"political_figure"}'::jsonb,true,NOW(),NOW()),
(gen_random_uuid(),'محمدجواد ظریف','وزیر خارجه پیشین','وزارت امور خارجه',ARRAY['ظریف','محمدجواد ظریف','وزیر خارجه'],ARRAY[]::text[],'recent','standard','#1565C0','{"external_id":"zarif","name":"محمدجواد ظریف","type":"political_figure"}'::jsonb,true,NOW(),NOW()),
(gen_random_uuid(),'فاطمه مهاجرانی','سخنگوی دولت','ریاست جمهوری',ARRAY['مهاجرانی','فاطمه مهاجرانی','سخنگوی دولت'],ARRAY[]::text[],'recent','standard','#880E4F','{"external_id":"mohajerani","name":"فاطمه مهاجرانی","type":"political_figure"}'::jsonb,true,NOW(),NOW()),
(gen_random_uuid(),'پیمان جبلی','رئیس سازمان صداوسیما','سازمان صداوسیما',ARRAY['جبلی','پیمان جبلی','صداوسیما'],ARRAY[]::text[],'recent','standard','#E65100','{"external_id":"jabali","name":"پیمان جبلی","type":"political_figure"}'::jsonb,true,NOW(),NOW()),
(gen_random_uuid(),'احمدرضا رادان','فرمانده انتظامی','نیروی انتظامی',ARRAY['رادان','احمدرضا رادان','نیروی انتظامی','پلیس'],ARRAY[]::text[],'recent','standard','#212121','{"external_id":"radan","name":"احمدرضا رادان","type":"political_figure"}'::jsonb,true,NOW(),NOW()),
(gen_random_uuid(),'ستار هاشمی','وزیر ارتباطات و فناوری اطلاعات','وزارت ارتباطات',ARRAY['ستار هاشمی','هاشمی','وزیر ارتباطات','فناوری اطلاعات'],ARRAY[]::text[],'recent','standard','#00838F','{"external_id":"hashemi_ict","name":"ستار هاشمی","type":"political_figure"}'::jsonb,true,NOW(),NOW()),
(gen_random_uuid(),'سید عباس عراقچی','وزیر خارجه','وزارت امور خارجه',ARRAY['عراقچی','سید عباس عراقچی','وزیر خارجه','دیپلماسی'],ARRAY[]::text[],'recent','enterprise','#1565C0','{"external_id":"araghchi","name":"سید عباس عراقچی","type":"political_figure"}'::jsonb,true,NOW(),NOW()),
(gen_random_uuid(),'سیدعلی مدنیزاده','وزیر اقتصاد','وزارت اقتصاد',ARRAY['مدنیزاده','سیدعلی مدنی زاده','وزیر اقتصاد','اقتصاد'],ARRAY[]::text[],'recent','standard','#2E7D32','{"external_id":"madanizadeh","name":"سیدعلی مدنیزاده","type":"political_figure"}'::jsonb,true,NOW(),NOW()),
(gen_random_uuid(),'ابراهیم حاتمیکیا','کارگردان سینما','سینمای ایران',ARRAY['حاتمیکیا','ابراهیم حاتمی کیا','سینما','فیلم'],ARRAY[]::text[],'recent','standard','#6A1B9A','{"external_id":"hatamikia","name":"ابراهیم حاتمیکیا","type":"public_figure"}'::jsonb,true,NOW(),NOW()),
(gen_random_uuid(),'الیاس حضرتی','معاون اطلاعرسانی دولت','ریاست جمهوری',ARRAY['حضرتی','الیاس حضرتی','اطلاع رسانی دولت'],ARRAY[]::text[],'recent','standard','#37474F','{"external_id":"hazrati","name":"الیاس حضرتی","type":"political_figure"}'::jsonb,true,NOW(),NOW()),
(gen_random_uuid(),'محمدباقر ذوالقدر','دبیر شورای امنیت ملی','شورای عالی امنیت ملی',ARRAY['ذوالقدر','محمدباقر ذوالقدر','شورای امنیت ملی'],ARRAY[]::text[],'recent','standard','#1A237E','{"external_id":"zolqadr","name":"محمدباقر ذوالقدر","type":"political_figure"}'::jsonb,true,NOW(),NOW()),
(gen_random_uuid(),'حمیدرضا حاجیبابایی','نماینده مجلس','مجلس شورای اسلامی',ARRAY['حاجی بابایی','حمیدرضا حاجی بابایی','نماینده مجلس'],ARRAY[]::text[],'recent','standard','#4E342E','{"external_id":"hajibabai","name":"حمیدرضا حاجیبابایی","type":"political_figure"}'::jsonb,true,NOW(),NOW()),
(gen_random_uuid(),'علیرضا دبیر','رئیس فدراسیون کشتی','فدراسیون کشتی',ARRAY['علیرضا دبیر','دبیر','فدراسیون کشتی','کشتی'],ARRAY[]::text[],'recent','standard','#BF360C','{"external_id":"dabir","name":"علیرضا دبیر","type":"public_figure"}'::jsonb,true,NOW(),NOW()),
(gen_random_uuid(),'محمدرضا صباغیان','نماینده یزد','مجلس شورای اسلامی',ARRAY['صباغیان','محمدرضا صباغیان','نماینده یزد'],ARRAY[]::text[],'recent','standard','#558B2F','{"external_id":"sabbagian","name":"محمدرضا صباغیان","type":"political_figure"}'::jsonb,true,NOW(),NOW()),
(gen_random_uuid(),'سید عزتالله ضرغامی','وزیر پیشین فرهنگ و ارشاد','وزارت فرهنگ و ارشاد اسلامی',ARRAY['ضرغامی','سید عزت الله ضرغامی','فرهنگ و ارشاد'],ARRAY[]::text[],'recent','standard','#E65100','{"external_id":"zarghami","name":"سید عزتالله ضرغامی","type":"political_figure"}'::jsonb,true,NOW(),NOW()),
(gen_random_uuid(),'امیر قلعهنویی','سرمربی تیم ملی','فدراسیون فوتبال',ARRAY['قلعه نویی','امیر قلعه نویی','تیم ملی','فوتبال'],ARRAY[]::text[],'recent','standard','#1B5E20','{"external_id":"ghalenoi","name":"امیر قلعهنویی","type":"public_figure"}'::jsonb,true,NOW(),NOW()),
(gen_random_uuid(),'امیرحسین ثابتی','فعال سیاسی','مستقل',ARRAY['ثابتی','امیرحسین ثابتی'],ARRAY[]::text[],'recent','standard','#37474F','{"external_id":"sabeti","name":"امیرحسین ثابتی","type":"political_figure"}'::jsonb,true,NOW(),NOW()),
(gen_random_uuid(),'علیرضا زاکانی','شهردار تهران','شهرداری تهران',ARRAY['زاکانی','علیرضا زاکانی','شهردار تهران','شهرداری'],ARRAY[]::text[],'recent','standard','#C62828','{"external_id":"zakani","name":"علیرضا زاکانی","type":"political_figure"}'::jsonb,true,NOW(),NOW()),
(gen_random_uuid(),'مصطفی تاجزاده','فعال سیاسی','مستقل',ARRAY['تاجزاده','مصطفی تاجزاده'],ARRAY[]::text[],'recent','standard','#00695C','{"external_id":"tajzadeh","name":"مصطفی تاجزاده","type":"political_figure"}'::jsonb,true,NOW(),NOW()),
(gen_random_uuid(),'محمدرضا باهنر','فعال سیاسی اصولگرا','مستقل',ARRAY['باهنر','محمدرضا باهنر','اصولگرا'],ARRAY[]::text[],'recent','standard','#4E342E','{"external_id":"bahonar","name":"محمدرضا باهنر","type":"political_figure"}'::jsonb,true,NOW(),NOW()),
(gen_random_uuid(),'علی نیکزاد','فعال سیاسی','مستقل',ARRAY['نیکزاد','علی نیکزاد'],ARRAY[]::text[],'recent','standard','#37474F','{"external_id":"nikzad","name":"علی نیکزاد","type":"political_figure"}'::jsonb,true,NOW(),NOW()),
(gen_random_uuid(),'مهدی کروبی','فعال سیاسی','مستقل',ARRAY['کروبی','مهدی کروبی'],ARRAY[]::text[],'recent','standard','#0277BD','{"external_id":"karroubi","name":"مهدی کروبی","type":"political_figure"}'::jsonb,true,NOW(),NOW()),
(gen_random_uuid(),'مهدی رسولی','مداح','مستقل',ARRAY['مهدی رسولی','رسولی','مداح'],ARRAY[]::text[],'recent','standard','#880E4F','{"external_id":"rasouli","name":"مهدی رسولی","type":"public_figure"}'::jsonb,true,NOW(),NOW()),
(gen_random_uuid(),'حسامالدین آشنا','مشاور پیشین رئیس جمهور','دولت',ARRAY['آشنا','حسام الدین آشنا','مشاور رئیس جمهور'],ARRAY[]::text[],'recent','standard','#006064','{"external_id":"ashna","name":"حسامالدین آشنا","type":"political_figure"}'::jsonb,true,NOW(),NOW()),
(gen_random_uuid(),'علیرضا قاسمیان','روحانی و فعال مذهبی','مستقل',ARRAY['قاسمیان','علیرضا قاسمیان','روحانی','مذهبی'],ARRAY[]::text[],'recent','standard','#4A148C','{"external_id":"ghasemian","name":"علیرضا قاسمیان","type":"public_figure"}'::jsonb,true,NOW(),NOW()),
(gen_random_uuid(),'احمد زیدآبادی','تحلیلگر سیاسی','مستقل',ARRAY['زیدآبادی','احمد زیدآبادی','تحلیلگر سیاسی'],ARRAY[]::text[],'recent','standard','#33691E','{"external_id":"zeidabadi","name":"احمد زیدآبادی","type":"public_figure"}'::jsonb,true,NOW(),NOW()),
(gen_random_uuid(),'صادق زیباکلام','استاد دانشگاه','دانشگاه تهران',ARRAY['زیباکلام','صادق زیباکلام','استاد دانشگاه'],ARRAY[]::text[],'recent','standard','#1565C0','{"external_id":"zibakalam","name":"صادق زیباکلام","type":"public_figure"}'::jsonb,true,NOW(),NOW()),
(gen_random_uuid(),'حسین افشین','معاون علم و فناوری رئیس جمهور','ریاست جمهوری',ARRAY['افشین','حسین افشین','علم و فناوری'],ARRAY[]::text[],'recent','standard','#00838F','{"external_id":"afshin","name":"حسین افشین","type":"political_figure"}'::jsonb,true,NOW(),NOW()),
(gen_random_uuid(),'سید احمد خاتمی','عضو خبرگان و امام جمعه موقت','مجلس خبرگان رهبری',ARRAY['سید احمد خاتمی','احمد خاتمی','امام جمعه','خبرگان'],ARRAY[]::text[],'recent','standard','#BF360C','{"external_id":"ahmad_khatami","name":"سید احمد خاتمی","type":"political_figure"}'::jsonb,true,NOW(),NOW())

ON CONFLICT ((promtic_identifier->>'external_id')) DO NOTHING;

COMMIT;
